import type { Config, Context } from '@netlify/functions'
import {
  currentUser,
  readAnonymousSession,
  unauthorized,
} from '../lib/auth.mts'
import { CREDIT_COSTS, InsufficientCreditsError, grant, spend } from '../lib/credits.mts'
import { buildFramePrompt } from '../lib/film.mts'
import { generateImage } from '../lib/images.mts'
import { checkRateLimit, sweepRateBuckets } from '../lib/rate-limit.mts'
import { loadProject, setFrameKey } from '../lib/projects.mts'
import { FRAME_PREFIX, frameStore } from '../lib/stores.mts'

export default async (req: Request, context: Context) => {
  const user = await currentUser()
  const anonymousSession = await readAnonymousSession(context)

  // A frame is only generated by whoever owns the project: a signed-in director
  // or an anonymous visitor whose trial session the project belongs to.
  if (!user && !anonymousSession) return unauthorized('Sign in to generate frames.')

  const limited = await checkRateLimit(req, 'frame', user?.identityId ?? null)
  if (limited) return limited

  let body: { projectId?: unknown; shot?: unknown; camera?: unknown; lighting?: unknown; mood?: unknown }
  try {
    body = await req.json()
  } catch {
    return Response.json({ error: 'Expected a JSON body.' }, { status: 400 })
  }

  const projectId = typeof body.projectId === 'string' ? body.projectId : ''
  const shotNumber = Number(body.shot)
  if (!projectId || !Number.isInteger(shotNumber)) {
    return Response.json({ error: 'projectId and shot are required.' }, { status: 400 })
  }

  const project = await loadProject(projectId)
  if (!project) {
    return Response.json({ error: 'Unknown project.' }, { status: 404 })
  }

  // Ownership: signed-in director matches their user id; anonymous visitor
  // matches the project's trial session.
  const ownsAsUser = Boolean(user && project.ownerId === user.id)
  const ownsAsAnon = Boolean(
    anonymousSession && project.anonymousSessionId === anonymousSession.id,
  )
  if (!ownsAsUser && !ownsAsAnon) {
    return Response.json({ error: 'That project belongs to another director.' }, { status: 403 })
  }

  const shot = project.shots.find((candidate) => candidate.number === shotNumber)
  if (!shot) {
    return Response.json({ error: 'Unknown shot.' }, { status: 404 })
  }

  // The workspace controls can override the look the story model chose.
  const directed = {
    ...shot,
    camera: typeof body.camera === 'string' && body.camera ? body.camera : shot.camera,
    lighting: typeof body.lighting === 'string' && body.lighting ? body.lighting : shot.lighting,
    mood: typeof body.mood === 'string' && body.mood ? body.mood : shot.mood,
  }

  const ref = `${projectId}:${shotNumber}`
  let balance: number | null = null

  // Only a signed-in director spends credits; the anonymous trial is free.
  if (user) {
    try {
      balance = await spend(user.id, CREDIT_COSTS.frame, 'frame', `Still — shot ${shotNumber}`, ref)
    } catch (error) {
      if (error instanceof InsufficientCreditsError) {
        return Response.json(
          {
            error: `That costs ${error.required} credits and you have ${error.balance}.`,
            insufficientCredits: true,
            required: error.required,
            balance: error.balance,
          },
          { status: 402 },
        )
      }
      throw error
    }
  }

  try {
    const image = await generateImage(buildFramePrompt(project, directed))

    // A fresh key per generation keeps regenerated frames immutably cacheable.
    const nonce = crypto.randomUUID().slice(0, 8)
    const key = `shot-${projectId}-${String(shotNumber).padStart(2, '0')}-${nonce}.${image.ext}`

    await frameStore().set(`${FRAME_PREFIX}${key}`, image.body)
    await setFrameKey(projectId, shotNumber, key)

    return Response.json({
      shot: shotNumber,
      key,
      frameUrl: `/api/frame/${key}`,
      model: image.model,
      balance,
    })
  } catch (error) {
    console.error(`generate-frame failed for ${projectId} shot ${shotNumber}:`, error)
    if (user) {
      const refunded = await grant(
        user.id,
        CREDIT_COSTS.frame,
        'refund',
        `Refund — shot ${shotNumber} failed`,
        ref,
      )
      return Response.json(
        { error: 'Frame generation failed. Your credits were refunded.', balance: refunded },
        { status: 502 },
      )
    }
    return Response.json({ error: 'Frame generation failed. Try again.' }, { status: 502 })
  }
}

export const config: Config = {
  path: '/api/generate-frame',
  method: 'POST',
}
